const selection_data = {
  Academic_program: [
    '',
    'BBA (Bachelor in Business Administration)',
    'DBA (Doctorate in Business Administration)',
    // 'DU (Diplome Universitaire en Recherche)',
    'EMBA (Executive Masters in Business Administration)',
    'EMFM (Executive Master in Financial Management)',
    'MBA (Master in Business Administration)',
    'MEMS (Master Executif en Management de la Santé)',
    'MENT (Masters in Entrepreneurship)',
    'MIAD (Master in International Affairs and Diplomacy)',
    'MIM (International Masters In Management)',
    'MSM (Mastère de Spécialisation en Marketing et Communication)',
  ],

  Academic_program_description: [
    'BBA (Bachelor in Business Administration)',
    'DBA (Doctorate in Business Administration)',
    // 'DU (Diplome Universitaire en Recherche)',
    'EMBA (Executive Masters in Business Administration)',
    'EMFM (Executive Master in Financial Management)',
    'MBA (Master in Business Administration)',
    'MEMS (Master Executif en Management de la Santé)',
    'MENT (Masters in Entrepreneurship)',
    'MIAD (Master in International Affairs and Diplomacy)',
    'MIM (International Masters In Management)',
    'MSM (Mastère de Spécialisation en Marketing et Communication)',
  ],

  Academic_period: ['2023/Yearly/Session 01'],
  PersonalInfo_title: ['', 'Mr', 'Mrs', 'Miss'],
  PersonalInfo_gender: ['', 'Male', 'Female'],

  // PersonalInfo_gender_fr: ['', 'Féminin', 'Masculin'],
  PersonalInfo_gender_fr: ['', 'Mâle', 'Femelle'],
  PersonalInfo_title_fr: [
    '',
    'M (Monsieur)',
    'Mlle (Mademoiselle)',
    'Mme (Madame)',
  ],

  personalinfo_country: [
    ' ',
    'Afghanistan',
    'Albania',
    'Algeria',
    'American Samoa',
    'Andorra',
    'Angola',
    'Anguilla',
    'Antarctica',
    'Antigua and Barbuda',
    'Argentina',
    'Armenia',
    'Aruba',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas (the)',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Belgium',
    'Belize',
    'Benin',
    'Bermuda',
    'Bhutan',
    'Bolivia (Plurinational State of)',
    'Bonaire, Sint Eustatius and Saba',
    'Bosnia and Herzegovina',
    'Botswana',
    'Bouvet Island',
    'Brazil',
    'British Indian Ocean Territory (the)',
    'Brunei Darussalam',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Cabo Verde',
    'Cambodia',
    'Cameroon',
    'Canada',
    'Cayman Islands (the)',
    'Central African Republic (the)',
    'Chad',
    'Chile',
    'China',
    'Christmas Island',
    'Cocos (Keeling) Islands (the)',
    'Colombia',
    'Comoros (the)',
    'Congo (the Democratic Republic of the)',
    'Congo (the)',
    'Cook Islands (the)',
    'Costa Rica',
    'Croatia',
    'Cuba',
    'Curaçao',
    'Cyprus',
    'Czechia',
    "Côte d'Ivoire",
    'Denmark',
    'Djibouti',
    'Dominica',
    'Dominican Republic (the)',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Equatorial Guinea',
    'Eritrea',
    'Estonia',
    'Eswatini',
    'Ethiopia',
    'Falkland Islands (the) [Malvinas]',
    'Faroe Islands (the)',
    'Fiji',
    'Finland',
    'France',
    'French Guiana',
    'French Polynesia',
    'French Southern Territories (the)',
    'Gabon',
    'Gambia (the)',
    'Georgia',
    'Germany',
    'Ghana',
    'Gibraltar',
    'Greece',
    'Greenland',
    'Grenada',
    'Guadeloupe',
    'Guam',
    'Guatemala',
    'Guernsey',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Heard Island and McDonald Islands',
    'Holy See (the)',
    'Honduras',
    'Hong Kong',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran (Islamic Republic of)',
    'Iraq',
    'Ireland',
    'Isle of Man',
    // 'Israel',
    'Italy',
    'Jamaica',
    'Japan',
    'Jersey',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    "Korea (the Democratic People's Republic of)",
    'Korea (the Republic of)',
    'Kuwait',
    'Kyrgyzstan',
    "Lao People's Democratic Republic (the)",
    'Latvia',
    'Lebanon',
    'Lesotho',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Macao',
    'Madagascar',
    'Malawi',
    'Malaysia',
    'Maldives',
    'Mali',
    'Malta',
    'Marshall Islands (the)',
    'Martinique',
    'Mauritania',
    'Mauritius',
    'Mayotte',
    'Mexico',
    'Micronesia (Federated States of)',
    'Moldova (the Republic of)',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Montserrat',
    'Morocco',
    'Mozambique',
    'Myanmar',
    'Namibia',
    'Nauru',
    'Nepal',
    'Netherlands (the)',
    'New Caledonia',
    'New Zealand',
    'Nicaragua',
    'Niger (the)',
    'Nigeria',
    'Niue',
    'Norfolk Island',
    'Northern Mariana Islands (the)',
    'Norway',
    'Oman',
    'Pakistan',
    'Palau',
    'Palestine, State of',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Philippines (the)',
    'Pitcairn',
    'Poland',
    'Portugal',
    'Puerto Rico',
    'Qatar',
    'Republic of North Macedonia',
    'Romania',
    'Russian Federation (the)',
    'Rwanda',
    'Réunion',
    'Saint Barthélemy',
    'Saint Helena, Ascension and Tristan da Cunha',
    'Saint Kitts and Nevis',
    'Saint Lucia',
    'Saint Martin (French part)',
    'Saint Pierre and Miquelon',
    'Saint Vincent and the Grenadines',
    'Samoa',
    'San Marino',
    'Sao Tome and Principe',
    'Saudi Arabia',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Sint Maarten (Dutch part)',
    'Slovakia',
    'Slovenia',
    'Solomon Islands',
    'Somalia',
    'South Africa',
    'South Georgia and the South Sandwich Islands',
    'South Sudan',
    'Spain',
    'Sri Lanka',
    'Sudan (the)',
    'Suriname',
    'Svalbard and Jan Mayen',
    'Sweden',
    'Switzerland',
    'Syrian Arab Republic',
    'Taiwan',
    'Tajikistan',
    'Tanzania, United Republic of',
    'Thailand',
    'Timor-Leste',
    'Togo',
    'Tokelau',
    'Tonga',
    'Trinidad and Tobago',
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'Turks and Caicos Islands (the)',
    'Tuvalu',
    'Uganda',
    'Ukraine',
    'United Arab Emirates (the)',
    'United Kingdom of Great Britain and Northern Ireland (the)',
    'United States Minor Outlying Islands (the)',
    'United States of America (the)',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Venezuela (Bolivarian Republic of)',
    'Viet Nam',
    'Virgin Islands (British)',
    'Virgin Islands (U.S.)',
    'Wallis and Futuna',
    'Western Sahara',
    'Yemen',
    'Zambia',
    'Zimbabwe',
    'Åland Islands',
  ],
  personalinfo_country_fr: [
    ' ',
    'Afghanistan',
    'Afrique du Sud',
    'Albanie',
    'Algérie',
    'Allemagne',
    'Aller',
    'Andorre',
    'Angola',
    'Anguille',
    'Antarctique',
    'Antigua-et-Barbuda',
    'Arabie Saoudite',
    'Argentine',
    'Arménie',
    'Aruba',
    'Australie',
    'Azerbaïdjan',
    'Bahamas',
    'Bahreïn',
    'Bangladesh',
    'Barbade',
    'Belgique',
    'Bélize',
    'Bénin',
    'Bermudes',
    'Bhoutan',
    'Biélorussie',
    'Birmanie',
    'Bolivie (État plurinational de)',
    'Bonaire, Saint Eustache et Saba',
    'Bosnie Herzégovine',
    'Botswana',
    'Brésil',
    'Brunei Darussalam',
    'Bulgarie',
    'Burkina Faso',
    'Burundi',
    'Cambodge',
    'Cameroun',
    'Canada',
    'Cap-Vert',
    'Chili',
    'Chine',
    'Chypre',
    'Colombie',
    'Comores',
    'Congo',
    'Congo (République démocratique du)',
    'Corée (la République de)',
    'Corée (République populaire démocratique de)',
    'Costa Rica',
    'Côte d’Ivoire',
    'Croatie',
    'Cuba',
    'Curacao',
    'Danemark',
    'Djibouti',
    'Dominique',
    'Egypte',
    'Emirats Arabes Unis',
    'Equateur',
    'Érythrée',
    'Espagne',
    'Estonie',
    'Eswatini',
    'États-Unis',
    'Ethiopie',
    'Fédération de Russie',
    'Fidji',
    'Finlande',
    'France',
    'Gabon',
    'Gambie',
    'Géorgie du Sud et îles Sandwich du Sud',
    'Géorgie',
    'Ghana',
    'Gibraltar',
    'Grèce',
    'Grenade',
    'Groenland',
    'Guadeloupe',
    'Guam',
    'Guatemala',
    'Guernesey',
    'Guinée Équatoriale',
    'Guinée',
    'Guinée-Bissau',
    'Guyane Française',
    'Guyane',
    'Haïti',
    'Honduras',
    'Hong Kong',
    'Hongrie',
    'Île Bouvet',
    'Île de Man',
    'île de noël',
    'Ile de Norfolk',
    'île Heard et îles McDonald',
    'Iles Aland',
    'Îles Caïmans',
    'îles Cocos (Keeling)',
    'Îles Cook',
    'Îles Falkland',
    'Îles Féroé',
    'Îles Mariannes du Nord',
    'Îles Marshall',
    'Îles mineures éloignées des États-Unis',
    'Îles Salomon',
    'Îles Turques et Caïques',
    'Îles Vierges (britanniques)',
    'Îles Vierges (États-Unis)',
    'Inde',
    'Indonésie',
    'Irak',
    'Iran (République islamique d’)',
    'Irlande',
    'Islande',
    'Italie',
    'Jamaïque',
    'Japon',
    'Jersey',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kirghizistan',
    'Kiribati',
    'Koweit',
    'L’Autriche',
    'Le Portugal',
    'Le Salvador',
    'Les Seychelles',
    'Lesotho',
    'Lettonie',
    'Liban',
    'Libéria',
    'Libye',
    'Liechtenstein',
    'Lituanie',
    'Luxembourg',
    'Macao',
    'Madagascar',
    'Malaisie',
    'Malawi',
    'Maldives',
    'Mali',
    'Malte',
    'Maroc',
    'Martinique',
    'Maurice',
    'Mauritanie',
    'Mayotte',
    'Mexique',
    'Micronésie (États fédérés de)',
    'Moldavie (République de)',
    'Monaco',
    'Mongolie',
    'Monténégro',
    'Montserrat',
    'Mozambique',
    'Namibie',
    'Nauru',
    'Népal',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'Niué',
    'Norvège',
    'Nouvelle Calédonie',
    'Nouvelle-Zélande',
    'Oman',
    'Ouganda',
    'Ouzbékistan',
    'Pakistan',
    'Palaos',
    'Palestine, État de',
    'Panama',
    'Papouasie Nouvelle Guinée',
    'Paraguay',
    'Pays-Bas',
    'Pérou',
    'Philippines',
    'Pitcairn',
    'Pologne',
    'Polynésie française',
    'Porto Rico',
    'Qatar',
    'République arabe syrienne',
    'République centrafricaine',
    'République de Macédoine du Nord',
    'République démocratique populaire lao',
    'République dominicaine',
    'Réunion',
    'Roumanie',
    'Royaume-Uni de Grande-Bretagne et d’Irlande du Nord',
    'Rwanda',
    'Sahara occidental',
    'Saint Barthélemy',
    'Saint Marin',
    'Saint-Christophe-et-Niévès',
    'Sainte Hélène, Ascension et Tristan da Cunha',
    'Sainte-Lucie',
    'Saint-Martin (partie française)',
    'Saint-Pierre-et-Miquelon',
    'Saint-Siège',
    'Saint-Vincent-et-les-Grenadines',
    'Samoa américaines',
    'Samoa',
    'Sao Tomé et Principe',
    'Sénégal',
    'Serbie',
    'Sierra Leone',
    'Singapour',
    'Sint Maarten (partie hollandaise)',
    'Slovaquie',
    'Slovénie',
    'Somalie',
    'Soudan',
    'Soudan du sud',
    'Sri Lanka',
    'Suède',
    'Suisse',
    'Surinam',
    'Svalbard et Jan Mayen',
    'Tadjikistan',
    'Taïwan',
    'Tanzanie, République-Unie de',
    'Tchad',
    'Tchéquie',
    'Terres Australes Françaises',
    'Territoire britannique de l’océan Indien ',
    'Thaïlande',
    'Timor oriental',
    'Tokélaou',
    'Tonga',
    'Trinité-et-Tobago',
    'Tunisie',
    'Turkménistan',
    'Turquie',
    'Tuvalu',
    'Ukraine',
    'Uruguay',
    'Vanuatu',
    'Venezuela',
    'Vietnam',
    'Wallis et Futuna',
    'Yémen',
    'Zambie',
    'Zimbabwe',
  ],
  personalinfo_country_fr_inter: [
    ' ',
    'Afghanistan',
    'Albanie',
    'Algérie',
    'Samoa américaines',
    'Andorre',
    'Angola',
    'Anguille',
    'Antarctique',
    'Antigua-et-Barbuda',
    'Argentine',
    'Arménie',
    'Aruba',
    'Australie',
    'L’Autriche',
    'Azerbaïdjan',
    'Bahamas',
    'Bahreïn',
    'Bangladesh',
    'Barbade',
    'Biélorussie',
    'Belgique',
    'Bélize',
    'Bénin',
    'Bermudes',
    'Bhoutan',
    'Bolivie',
    'Bonaire, Saint Eustache et Saba',
    'Bosnie Herzégovine',
    'Botswana',
    'Île Bouvet',
    'Brésil',
    'Territoire britannique de l’océan Indien',
    'Brunei Darussalam',
    'Bulgarie',
    'Burkina Faso',
    'Burundi',
    'Cap-Vert',
    'Cambodge',
    'Cameroun',
    'Canada',
    'Îles Caïmans',
    'République centrafricaine',
    'Tchad',
    'Chili',
    'Chine',
    'L’île de noël',
    'îles Cocos (Keeling)',
    'Colombie',
    'Comores',
    'Congo (République démocratique du)',
    'Congo',
    'Îles Cook',
    'Costa Rica',
    'Croatie',
    'Cuba',
    'Curacao',
    'Chypre',
    'Tchéquie',
    'Côte d’Ivoire',
    'Danemark',
    'Djibouti',
    'Dominique',
    'République dominicaine',
    'Equateur',
    'Egypte',
    'Le Salvador',
    'Guinée Équatoriale',
    'Érythrée',
    'Estonie',
    'Eswatini',
    'Ethiopie',
    'Îles Falkland',
    'Îles Féroé',
    'Fidji',
    'Finlande',
    'France',
    'Guyane Française',
    'Polynésie française',
    'Terres Australes Françaises',
    'Gabon',
    'Gambie (la)',
    'Géorgie',
    'Allemagne',
    'Ghana',
    'Gibraltar',
    'Grèce',
    'Groenland',
    'Grenade',
    'Guadeloupe',
    'Guam',
    'Guatemala',
    'Guernesey',
    'Guinée',
    'Guinée-Bissau',
    'Guyane',
    'Haïti',
    'île Heard et îles McDonald',
    'Saint-Siège (le)',
    'Honduras',
    'Hong Kong',
    'Hongrie',
    'Islande',
    'Inde',
    'Indonésie',
    'Iran (République islamique d’)',
    'Irak',
    'Irlande',
    'Île de Man',
    // 'Israël',
    'Italie',
    'Jamaïque',
    'Japon',
    'Jersey',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    'Corée (République populaire démocratique de)',
    'Corée (la République de)',
    'Koweit',
    'Kirghizistan',
    'République démocratique populaire lao',
    'Lettonie',
    'Liban',
    'Lesotho',
    'Libéria',
    'Libye',
    'Liechtenstein',
    'Lituanie',
    'Luxembourg',
    'Macao',
    'Madagascar',
    'Malawi',
    'Malaisie',
    'Maldives',
    'Mali',
    'Malte',
    'Îles Marshall (les)',
    'Martinique',
    'Mauritanie',
    'Maurice',
    'Mayotte',
    'Mexique',
    'Micronésie (États fédérés de)',
    'Moldavie (République de)',
    'Monaco',
    'Mongolie',
    'Monténégro',
    'Montserrat',
    'Maroc',
    'Mozambique',
    'Birmanie',
    'Namibie',
    'Nauru',
    'Népal',
    'Pays-Bas (les)',
    'Nouvelle Calédonie',
    'Nouvelle-Zélande',
    'Nicaragua',
    'Niger (le)',
    'Nigeria',
    'Niué',
    'L’ile de Norfolk',
    'Îles Mariannes du Nord (les)',
    'Norvège',
    'Oman',
    'Pakistan',
    'Palaos',
    'Palestine, État de',
    'Panama',
    'Papouasie Nouvelle Guinée',
    'Paraguay',
    'Pérou',
    'Philippines (les)',
    'Pitcairn',
    'Pologne',
    'Le Portugal',
    'Porto Rico',
    'Qatar',
    'République de Macédoine du Nord',
    'Roumanie',
    'Fédération de Russie (la)',
    'Rwanda',
    'Réunion',
    'Saint Barthélemy',
    'Sainte Hélène, Ascension et Tristan da Cunha',
    'Saint-Christophe-et-Niévès',
    'Sainte-Lucie',
    'Saint-Martin (partie française)',
    'Saint-Pierre-et-Miquelon',
    'Saint-Vincent-et-les-Grenadines',
    'Samoa',
    'Saint Marin',
    'Sao Tomé et Principe',
    'Arabie Saoudite',
    'Sénégal',
    'Serbie',
    'Les Seychelles',
    'Sierra Leone',
    'Singapour',
    'Sint Maarten (partie hollandaise)',
    'Slovaquie',
    'Slovénie',
    'Îles Salomon',
    'Somalie',
    'Afrique du Sud',
    'Géorgie du Sud et îles Sandwich du Sud',
    'Soudan du sud',
    'Espagne',
    'Sri Lanka',
    'Soudan (le)',
    'Surinam',
    'Svalbard et Jan Mayen',
    'Suède',
    'Suisse',
    'République arabe syrienne',
    'Taïwan',
    'Tadjikistan',
    'Tanzanie, République-Unie de',
    'Thaïlande',
    'Timor oriental',
    'Aller',
    'Tokélaou',
    'Tonga',
    'Trinité-et-Tobago',
    'Tunisie',
    'Turquie',
    'Turkménistan',
    'Îles Turques et Caïques (les)',
    'Tuvalu',
    'Ouganda',
    'Ukraine',
    'Emirats Arabes Unis (les)',
    'Royaume-Uni de Grande-Bretagne et d’Irlande du Nord (le)',
    'Îles mineures éloignées des États-Unis',
    'États-Unis',
    'Uruguay',
    'Ouzbékistan',
    'Vanuatu',
    'Venezuela (République bolivarienne du)',
    'Vietnam',
    'Îles Vierges (britanniques)',
    'Îles Vierges (États-Unis)',
    'Wallis et Futuna',
    'Sahara occidental',
    'Yémen',
    'Zambie',
    'Zimbabwe',
    'Iles Aland',
  ],

  Address_Address_type: ['', 'Home Address'],
  Address_Address_type_fr: ['', 'Adresse du domicile'],
  personalinfo_maritalstatus: ['', 'Single', 'Married', 'Divorced', 'Widowed'],
  personalinfo_maritalstatus_fr: [
    '',
    'Célibataire',
    'Marié(e)',
    'Divorcé(e)',
    'Veuf(ve)',
  ],
  emergencycontact_prefix: ['', 'Mr', 'Mrs', 'Miss'],
  emergencycontact_prefix_fr: [
    '',
    'M (Monsieur)',
    'Mlle (Mademoiselle)',
    'Mme (Madame)',
  ],
  emergencycontact_relationship: [
    '',
    'Brother',
    'Child',
    'Doctor',
    'Employer',
    'Father',
    'Grandparent',
    'Mother',
    'Neighbor',
    'Relative',
    'Spouse',
    'Friend',
    'Sister',
    'Guardian',
    'Other',
  ],

  emergencycontact_relationship_fr: [
    '',
    'Frère',
    'Enfant',
    'Docteur',
    'Employeur',
    'Père',
    'Grand-parent',
    'Mère',
    'Voisin',
    'Relatif',
    'Conjoint',
    'Ami',
    'Sœur',
    'Gardien',
    'Autre',
  ],
  emergencycontact_diseasetype: [
    '',
    'Attention deficit hyperactivity disorder (ADHD)',
    'Hearing Impaired',
    'Learning Disability',
    'Mobility Impaired',
    'Vision Impaired',
    'Other',
  ],
  emergencycontact_diseasetype_fr: [
    '',
    "Trouble déficit de l'attention avec hyperactivité (TDAH)",
    'Déficience auditive',
    "Trouble d'apprentissage",
    'Mobilité réduite',
    'Déficience visuelle',
    'Autre',
  ],
  education_baccalaureateoption: [
    '',
    'Economique',
    'Littéraire',
    'Scientifique',
    'Other',
  ],
  education_baccalaureateoption_fr: [
    '',
    'Economique',
    'Littéraire',
    'Scientifique',
    'Autre',
  ],
  education_degreelevel_BBA: [
    '',
    'Baccalauréat Libanais',
    'Baccalauréat Français',
    'Baccalauréat Français et Baccalauréat',
    'Libanais Autre Equivalent',
  ],

  education_degreelevel_BBA_fr: [
    '',
    'Baccalauréat Libanais',
    'Baccalauréat Français',
    'Baccalauréat Français et Baccalauréat',
    'Libanais Autre Equivalent',
  ],

  education_degreelevel: ['', 'Doctorat', 'Master', 'Licence'],
  education_degreelevel_fr: ['', 'Doctorat', 'Master', 'Licence'],
  education_institution: [
    '',
    'Amjad High school',
    'Brummana High School',
    'Collège de la Sainte Famille Fanar',
    'Collège des apôtres - Jounieh',
    'Collège des Frères Maristes Champville',
    'Collège des Frères Mont La Salle',
    'Collège des Pères Antonins',
    'Collège des Saints-Coeurs Kfarhbab',
    'Collège des Sœurs des Saints-Cœurs Ain Najm',
    'Collège Des Soeurs Du Rosaire Mountazah',
    'Collège du Carmel Saint Joseph',
    'Collège du Sacré-Coeur',
    'Collège Elysée',
    'Collège International du Montana',
    'Collège lamartine',
    'Collège Louise Wegmann',
    'Collège Melankton and Haig Arslanian',
    'Collège Melkart',
    'Collège national du Chouf',
    'Collège Notre Dame de Jamhour',
    'Collège Notre Dame de Nazareth',
    'Collège Notre Dame des Apôtres - Rawda',
    'Collège Notre-Dame de Louaizé',
    'Collège of the North Atlantic - Qatar',
    'Collège Protestant Français',
    'Collège Saint François des Capucins',
    'Collège Saint Joseph - Antoura',
    'Collège Stanislas de Montréal',
    'Dalum Dairy School',
    'Ecole Européenne de Bruxelles 1',
    'Ecole Française Internationale de Riyadh',
    'Ecole Franco-Chypriote',
    'Ecole Montaigne',
    'Ecole Secondaire des Filles de la Charité',
    'Empire State Collège of New York',
    'Excelsior College',
    'Houssam Eddine Hariri High School',
    'IML-Institution Moderne du Liban',
    'Institut Technique Industriel - Dekwaneh',
    'International College',
    "L'Athénée De Beyrouth",
    'Le Lycée National',
    'LWIS City International School',
    'Lycée Abdel Kader',
    'Lycée Al Manar',
    'Lycée de Ville',
    'Lycée Français de Lomé',
    'Lycée Français de Tananarive',
    'Lycée Français du Koweit',
    'Lycée Français international de Pékin',
    'Lycée Français International Elite',
    'Lycée Français International Georges Pompidou',
    'Lycée Français Internationale de Djeddah',
    'Lycée Français Louis Massignon',
    'Lycée Français René-Descartes',
    'Lycée Franco-Libanais',
    'Lycée Franco-Libanais Alphonse de Lamartine',
    'Lycée Franco-Libanais Nahr Ibrahim',
    'Lycée Franco-Libanais Verdun',
    'Lycée Franco-Qatarien Voltaire',
    'Lycée ITEC Boisfleury',
    'Lycée Lyautey ( Casablanca)',
    'Lycée Sainte-UrsuleLycée Sainte-Ursule',
    'Middlebury Collège',
    'Regent College',
    'Sagesse Saint Jean Brasilia',
    'Saint Joseph School Cornet Chahwan',
    "St. George's School",
    'Other',
  ],
  education_institution_fr: [
    '',
    'Amjad High school',
    'Brummana High School',
    'Collège de la Sainte Famille Fanar',
    'Collège des apôtres - Jounieh',
    'Collège des Frères Maristes Champville',
    'Collège des Frères Mont La Salle',
    'Collège des Pères Antonins',
    'Collège des Saints-Coeurs Kfarhbab',
    'Collège des Sœurs des Saints-Cœurs Ain Najm',
    'Collège Des Soeurs Du Rosaire Mountazah',
    'Collège du Carmel Saint Joseph',
    'Collège du Sacré-Coeur',
    'Collège Elysée',
    'Collège International du Montana',
    'Collège lamartine',
    'Collège Louise Wegmann',
    'Collège Melankton and Haig Arslanian',
    'Collège Melkart',
    'Collège national du Chouf',
    'Collège Notre Dame de Jamhour',
    'Collège Notre Dame de Nazareth',
    'Collège Notre Dame des Apôtres - Rawda',
    'Collège Notre-Dame de Louaizé',
    'Collège of the North Atlantic - Qatar',
    'Collège Protestant Français',
    'Collège Saint François des Capucins',
    'Collège Saint Joseph - Antoura',
    'Collège Stanislas de Montréal',
    'Dalum Dairy School',
    'Ecole Européenne de Bruxelles 1',
    'Ecole Française Internationale de Riyadh',
    'Ecole Franco-Chypriote',
    'Ecole Montaigne',
    'Ecole Secondaire des Filles de la Charité',
    'Empire State Collège of New York',
    'Excelsior College',
    'Houssam Eddine Hariri High School',
    'IML-Institution Moderne du Liban',
    'Institut Technique Industriel - Dekwaneh',
    'International College',
    "L'Athénée De Beyrouth",
    'Le Lycée National',
    'LWIS City International School',
    'Lycée Abdel Kader',
    'Lycée Al Manar',
    'Lycée de Ville',
    'Lycée Français de Lomé',
    'Lycée Français de Tananarive',
    'Lycée Français du Koweit',
    'Lycée Français international de Pékin',
    'Lycée Français International Elite',
    'Lycée Français International Georges Pompidou',
    'Lycée Français Internationale de Djeddah',
    'Lycée Français Louis Massignon',
    'Lycée Français René-Descartes',
    'Lycée Franco-Libanais',
    'Lycée Franco-Libanais Alphonse de Lamartine',
    'Lycée Franco-Libanais Nahr Ibrahim',
    'Lycée Franco-Libanais Verdun',
    'Lycée Franco-Qatarien Voltaire',
    'Lycée ITEC Boisfleury',
    'Lycée Lyautey ( Casablanca)',
    'Lycée Sainte-UrsuleLycée Sainte-Ursule',
    'Middlebury Collège',
    'Regent College',
    'Sagesse Saint Jean Brasilia',
    'Saint Joseph School Cornet Chahwan',
    "St. George's School",
    'Autre',
  ],

  education_schoolgrades_range: [
    '1 to 5',
    '6 to 10',
    '11 to 20',
    '21 to 30',
    '31 to 40',
  ],

  source_en: [
    'Email',
    'Radio',
    'TV',
    'Search on internet',
    'Online adverstisement',
    'On campus event',
    'Word of mouth',
    'Information Meeting',
    'Facebook',
    'Instagram',
    'Linkedin',
    'Twitter',
    'Magazine and Newspaper',
    'Student/Job fair',
    'ESA website',
    'Alumni',
    'Other',
  ],
  source_fr: [
    'E-mail',
    'Radio',
    'Télévision',
    'Recherche sur internet',
    'Publicité en ligne',
    'Evénement sur campus',
    'Bouche à oreille',
    'Réunion d’information',
    'Facebook',
    'Instagram',
    'Linkedin',
    'Twitter',
    'Magazine et Journal',
    'Salon étudiant',
    'Site de l’ESA',
    'Ancien étudiant',
    'Autre',
  ],
  experience_company_fr: [
    '',
    '301 Entertainment',
    '3A Solutions Group',
    'A.N. Boukather',
    'A+ Management',
    'Abbott Laboratories',
    'Abboud Law Offices',
    'ABC',
    'Abela Assurances',
    'Abi Haidar Law Firm',
    'Abi Haila & Issa Co',
    'Abington Advisory',
    'Abniah',
    'Abou Jaoude and Associates Law Firm',
    'Aboujaoudé Hospital',
    'Abou Sleiman & Co',
    'ACT- Automation & Computer Technologies',
    'ACTED',
    'Acteos Liban',
    'Actuscope',
    'Adir Insurance',
    'Adline Media Network',
    'ADMIC',
    'ADPI Middle East',
    'Adwan Law Firm',
    'Agility Logistics',
    'Ahli International Bank',
    'AIG (Africa International Group)',
    'Air France',
    'Air Liquide',
    'Aishti',
    'Aksys Capital',
    'Al Akhbar',
    'Al Borj Hospital',
    'Al Makassed General Hospital',
    'Al Manar University',
    'Al Mashrek Insurance',
    'Al Mawarid Bank',
    'Al Mayyas Hospital',
    'Al Rassoul Al Azam Hospital',
    'Al Salam Hospital',
    'Al Wadi Al Akhdar',
    'Alaeddine Hospital',
    'Alargan',
    'Albani Engineering and Contracting',
    'Albert Massaad',
    'Alem & Associates',
    'Alfa Telecommunications',
    'Algorithm',
    'Ali Al Aidarous International Legal Practice',
    'Alico (American Life Insurance Company)',
    'Allianz SNA',
    'AltCity',
    'Alternite',
    'Al-Zahraa Hospital University Medical Center',
    'AMB Group',
    'Ambassade de Belgique au Liban',
    'Ambassade de France au Liban',
    'American Express',
    'AMNCC Law Firm',
    'ANGLESDIFFERING',
    'Annahar',
    'Antoine Chakhtoura Law Office',
    'Apave',
    'Apliman',
    'Apps2you',
    'Appwe Offices',
    'Arab BVank',
    'Arab Finance House',
    'Arab Scientific Publishers',
    'Arabia Insurance',
    'Arago Beirut Law Firm',
    'Aramex',
    'Arcenciel (NGO)',
    'Arope Insurance',
    'Assaf Law Firm',
    'Assurex Insurance and Reinsurance',
    'AstraZeneca',
    'Astrolabe ICT',
    'AUB',
    'AUBMC',
    'Auto Mall',
    'Automatix',
    'Averda House Beirut',
    'Axa Middle East',
    'Ayadina Association',
    'Azadea Group',
    'Bader Farhat Law Office',
    'Baker Tilly Zacca',
    'Banako',
    'Bank Audi',
    'Bank of Beirut',
    'Bankmed',
    'Banque BEMO',
    'Banque de Syrie et du Liban Finance',
    'Banque du Liban',
    'Banque Libano-Francaise',
    'Barclays Wealth',
    'Basil Soda',
    'Bassoul Heneine',
    'BBAC',
    'BCC Logistics',
    'BCom Offshore',
    'Beam International',
    'Beirut Container Terminal Consortium (BCTC)',
    'Beirut General Hospital',
    'Bel Group',
    'Best Assistance',
    'Best Food Plus Group',
    'Best Seller United Middle East',
    'Beyond Reform and Development',
    'BIM-ME',
    'Bint Jbeil Governmental Hospital',
    'Bioscientia',
    'Black Unicorn Media FZ LLC',
    'BLC Bank',
    'Bleu Design Consultants',
    'B-Line Medical',
    'BLOM Bank',
    'Blossom Agency',
    'BML - Banque Misr Liban',
    'Boecker',
    'Bou Khalil Societe Moderne',
    'Boulos Law Firm',
    'Boustany Trading and Services',
    'Brasserie Almaza',
    'BRICS',
    'Bringerr',
    'Bristish Council',
    'British American Tobacco (BAT)',
    'Broadgate Advisers',
    'Brokers XP',
    'BSEC - Bemo Securitization',
    'BUS Architects',
    'BUTEC',
    'Byblos Bank',
    'Byzance',
    'Cadis',
    'Capital Banking Solutions',
    'Cartier',
    'CD Log',
    'Cedarland Hotel',
    'Cedarwood Advisors',
    'Centre Hospitalier de Bhannes',
    'Century Travel',
    'CFI Lebanon - Credit Financier Invest',
    'Chalhoub Group',
    'Chanel',
    'Chaoui Holding',
    'Chedid Capital Holding',
    'Chehab Law Firm',
    'Chemonics Lebanon',
    'Chris and George Consulting and Trading',
    'Chronic Care Center',
    'Ciment de Sibline',
    'Cimenterie Nationale',
    'Clemenceau Medical Center - CMC',
    'Clinical and Diagnostics Logistics',
    'Clinique Du Levant',
    'CMA CGM',
    'CNAM',
    'CNR Marketing Group',
    'Code Fish',
    'Coeficient',
    'Collège Des Soeurs De Sainte Thérèse - Amioun',
    'Commercial Insurance',
    'Communication & Media Consulting Services',
    'Concrete Plus',
    'Conserves Modernes Chtaura',
    'Contracting & Trading Co C.A.T.',
    'Cortbawi Hospital',
    'Corum Group Ltd.',
    'Cre8mania - Digital Agency',
    'Credex',
    'Credit Bank',
    'Credit Financier',
    'Credit Libanais',
    'Credit Suisse',
    'Crepaway',
    'Crown Flour Mills',
    'CSCBank',
    'CSR (Al Ahli Holding Group)',
    'Dagher Capital',
    'Dallaa General Hospital',
    'Dar Al Shifaa Hospital',
    'Dar El Kotob',
    'Dataquest',
    'Debbane Saikali Group',
    'Debbas Group',
    'Debi.R',
    'Debs & Associates Law Firm',
    'Degrémont',
    'Deloitte',
    'Design Engineering Partners',
    'Destinators',
    'DG Jones And Partners',
    'Diageo',
    'Digmatech',
    'Dip To Color sal',
    'Diwanee',
    'DNA Training &Consulting',
    'Doctors Without Borders',
    'Dow',
    'Dubai Financial Service Authority',
    'Edarat Group',
    'Edenred Liban',
    'Eiwan United Trading &Contracting',
    'El Youssef Hospital Center',
    'Eli Lilly',
    'Endeavor Lebanon',
    'ENSOL',
    'eProseed Group',
    'Eptalex - Aziz Torbey Law Firm',
    'Ericsson',
    'E-Square Architects',
    'Etablissements Antoine Massoud (EAM)',
    'Exotica',
    'Experts Health Beauty',
    'Faden Advertising Ageny',
    'Fakhry General Contracting',
    'Fakhry Law Firm',
    'Farah & Chidiac Law Firm',
    'Fares Group Law Firm',
    'Fast Bollore Logistics',
    'Fattal Group',
    'Fawaz Holding',
    'Fayad Food Consulting',
    'Fenicia Bank',
    'FFA Private Bank',
    'Fidelity Insurance',
    'Firefly International',
    'First National Bank',
    'FISHEYE MediaLab',
    'FMCP',
    'Fondation Saradar',
    'FOO_',
    'Four Points by Sheraton',
    'Four Seasons Hotel Beirut',
    'Fransabank',
    'Freelance',
    'FXCM Trading',
    'G. Tamer Holding',
    'Gates Corporation',
    'Gazprombank',
    'Gefinor Rotana',
    'Gemayel Law Firm',
    'General Medical Equipment',
    'General Reinsurance Services',
    'GeoSpatial Minds',
    'Girardo Co.',
    'Global Protection Corp.',
    'GlobalCom Holding',
    'GlobeMed',
    'Globini for Travel & Tourism',
    'Gras Savoye Liban',
    'Green & Co.',
    'Greenpeace',
    'GS Stores',
    'GSS International',
    'Gulf Finance & Investment Company',
    'GWR Consulting',
    'Habib Betinjaneh Est.',
    'Haddad & Associates Law Firm',
    'Hafez Group',
    'Harb Law Firm',
    'Haroun Studios',
    'Havas Group',
    'Havi Global Solutions',
    'Hayek Hospital',
    'Hoballah Law Firm',
    'HODICO',
    'Holcim',
    'HOLDAL Group',
    'Home Mobility',
    'Hôpital Al Koura',
    'Hôpital des Soeurs du Rosaire',
    'Hôpital du Sacré Coeur',
    'Hopital Haroun',
    'Hôpital Hôtel Dieu de France',
    'Hôpital Saint Georges - Ajaltoun',
    'Hôpital Saint Joseph',
    'HSBC',
    'I Production',
    'ICTN',
    'ID Project',
    'Impact BBDO',
    'Imperial Jet',
    'INDEVCO Group',
    'Inria',
    'Institut des Finances Basil Fuleihan',
    'Integrated Systems',
    'Integrity',
    'InterContinental Phoenicia Beirut',
    'Intermedic (Jean Farah & Co.)',
    'International Consolidated Contractor (ICC)',
    'International Publishers',
    'Intrasky',
    'Invigo',
    'IP Engineering Pro',
    'IPEC',
    'IPSOS',
    'IPT Powertech Group',
    'ITec',
    'ITG Holding',
    'Jabal Amel Hospital',
    'Jetex',
    'Jimmy Choo',
    'Joaillerie Moukarzel',
    'Joe Fish Agency',
    'Johnson and Johnson',
    'K Group Holding',
    'Kafalat',
    'Kallas Law Firm',
    'Kallassi Group',
    'Kawas Consulting',
    'Kazar - Marble, Granite & Fireplace',
    'KBP-Biomak',
    'Kearney',
    'Keeward',
    'Kempinski Summerland Hotel &Resort',
    'Kettaneh Group',
    'Khatib and Alami',
    'Khoury General Hospital',
    'Khoury Home',
    'KidzMondo',
    'Kiyan Art',
    'Klimos Law Firm',
    'Knauf SCC',
    'Knowledge Development Company',
    'KStars Cosmetics',
    'La 16 Sal - Insurance Consultants',
    'La Constructa',
    'La Ferme Saint Jacques',
    'La Regie Libanaise de Publicité',
    'Laceco',
    "L'Atelier RosArt",
    'LAU - Lebanese American University',
    'Leader Group',
    'Lebanese Army',
    'Lebanese Development Network - LDN',
    'Lebanese Franchise Association',
    'Lebanese League for Women in Business (LLWB)',
    'Lebanese Order of Physicians',
    'Lebanese Red Cross',
    'Lebanese Swiss Bank',
    'Lebanese University',
    'Lebanon and Gulf Bank (LGB)',
    'Lebanon Heart Hospital',
    'LebVision',
    'Leo Burnett',
    'Les Plumes Galerie Elsie Braidi',
    'Les Volailles De Batroun',
    'Lesco ME',
    'Levant Law Practice',
    'Level 5 Holding',
    'LIA Insurance',
    "Libano Française d'Ingenierie (LFI)",
    'Libano-Suisse Insurance',
    'LibanPost',
    'Libnor',
    'Librairie Antoine',
    'Librairie Du Liban Publishers',
    'Librairie Orientale',
    'Librairie Stephan',
    'LITAT Group',
    "L'OR Espresso",
    'Luxury Selections',
    'M&C Saatchi',
    'M. Ezzat Jallad & Fils',
    'MaaDATA Group',
    'Maalouf and Associates Law Firm',
    'Machmouchi & Associates Law Firm',
    'Makassed University of Beirut',
    'Malia Group',
    'MaliaTec',
    'Maliks',
    'MAN Enterprise',
    'Manzil Home Health Services',
    'Maria Group',
    'Master Capital group',
    'MATEC',
    'Matta et Associés',
    'MEAB',
    'Medevco',
    'Medgulf',
    'Medial Collateral Ligament (MCL)',
    'MEDICA',
    'Medical Shares Trading',
    'Memac Ogilvy',
    'Mena Marketing',
    'Mentor Arabia',
    'Mersaco',
    'Method M',
    'Mets Holding',
    'MG Holding',
    'Middle East Airlines (MEA)',
    'Middle East Capital Group (MECG)',
    'Mideast Assistance International',
    'Miel du Levant',
    'Mike Sport',
    'Mind The Gap',
    'Ministry of Education and Higher Education',
    'MIRROS Communications',
    'MItchell Cosmetics Inc.',
    'Mitsulift and Equipment',
    "MK Cuisines D'allemagne",
    'Mm Hechme Logistics',
    'Mokbel Group',
    'Momentis Systems',
    'Monla Hospital',
    'Monty Mobile',
    'Mouawad Library',
    'Mount Lebanon Hospital',
    'Mövenpick Hotels & Resorts',
    'Murex',
    'Najjar Hospital',
    'Najm Engineering &Contracting',
    'Nasser &Associates Law Firm',
    'Natagri',
    'Natgaz',
    'National Automated Systems N.A.S.',
    'National Bank of Abu Dhabi',
    'National Bank of Kuwait',
    'National Social Security Fund (NSSF)',
    'NavLink',
    'Near East Consulting Group',
    'Nehme & Associates',
    'Nesma Trading Co. Ltd.',
    'Nestlé',
    'Netiks International',
    'New Mazloum Hospital',
    'Nexmedia',
    'Nexty Electronics',
    'Nielsen Holdings',
    'Nini Hospital',
    'Nobrand Agency',
    'Noueihed Law Firm',
    'Noura',
    'Obegi Consumer Products Holding',
    'Obegi Group',
    'Octapharma AG',
    'Office of Inspector General',
    'Optimedia',
    'Optiva',
    'Oracle',
    'Orange Business Services',
    'Oursin Boursin',
    'Patchi',
    'Peri Lebanon',
    'Perrin Paris',
    'Petroserv Limited',
    'Pharma Group',
    'Pharmacie Sacré Coeur',
    'Pharmadex',
    'Pharmaline',
    'Pharmamed',
    'Phoenicia Aer Rianta (PAC)',
    'Phoenicia University',
    'Phoenix Clinical Research',
    'Pikasso',
    'Plan Bee Architecture',
    'Plexi Pro',
    'Porsche',
    'Powertech',
    'Pragma Group',
    'Procter & Gamble Levant',
    'Prodent',
    'Promedz',
    'Promo House Group',
    'PSI',
    'Purple Martin',
    'QuanTech',
    'Raëd Abillama Architects',
    'Raee Hospital',
    'Rafic Gazzaoui & Co.',
    'Rafik Hariri University Hospital',
    'Rahma Medical Center',
    'Raidy Printing Group',
    'Ras Beirut Food Concepts',
    'Rectangle Jaune',
    'RELKO Ltd.',
    'REMCO',
    'Rim',
    'Roadster diner & Deek Duke',
    'Roche Lebanon',
    'Roger Najjar Law Firm',
    'Rotana Hotels',
    'RPS Research France',
    'RSM Global',
    'Russian Post',
    'SAAS Lawyers',
    'SABIS Educational Services',
    'Sabre Travel Network',
    'Safieddine Khoury & Jezzini Law Firm',
    'Safir Heliopolitan',
    'Sahel General Hospital',
    'Saint Charles Hospital',
    'Saint George Hospital',
    'Sakr Power Generation',
    'Sakr Real Estate',
    'Saltek - Bakery Equipment',
    'Sama Lel Tayaran',
    'Sami Nahas Law Firm',
    'Sami Pharmacy',
    'Samir Khairallah & Partners',
    'Sanofi Aventis',
    'Saradar Bank',
    'Sarkis Group International',
    'Saudi Build Co.',
    'Sawan Jewellery',
    'Schneider Electric',
    'SDC Group',
    'Sealine',
    'SEG Lebanon',
    'Segenius',
    'Setraco Group',
    'SGR',
    'Signature Productions',
    'Sir Dannieh Governmental Hospital',
    'Site Technology',
    'SM Architects',
    'SMLC PepsiCo',
    'SNB - Saudi National Bank',
    'Snowball',
    'Société Générale de Banque au Liban (SGBL)',
    'Société Orientale des Métaux Précieux (SOMP)',
    'Socodile Holding',
    'Sodamco Holding',
    'SoftMind',
    'Solidere',
    'Somfy Lebanon',
    'Spine Care Centre',
    'Spinneys',
    'SSK Law Firm',
    'SSS - Smart System Solution',
    'Stad Beirut',
    'Standard Chartered',
    'Storm Advertising & Design',
    'Sukleen',
    'SV Properties & Construction',
    'Tamyras',
    'TaraDomus',
    'Technica International',
    'Tehaco',
    'Tel Chiha Hospital',
    'Telesupport International (TSI)',
    'Terre Brune Hotel',
    'The EuroMena Funds',
    'The Lebanese Credit Insurer (LCI)',
    'The Webcor Group',
    'Thomson Reuters Corporation',
    'Tohme Law Firm',
    'Total Liban',
    'Trafigura Beheer BV',
    'Triple C',
    'Tripoli Governmental Hospital',
    'TVM Capital Healthcare',
    'Tyan & Zgheib Law Firm',
    'Unilever',
    'UNIPAK',
    'Unipharm',
    'Unitech International',
    'United Nations Development Programme (UNDP)',
    'United Nations Interim Force In Lebanon - UNI',
    'USJ - Saint Joseph University',
    'Vita Nova',
    'Vitality Clinic',
    'Voice of Lebanon',
    'Waked Law Firm',
    'Walid Haddad & Associates Law Firm',
    'War Child Holland',
    'Wardieh Holdings Inc Head-Office',
    'Wataniya Group',
    'Wezank',
    'Wheelers.me',
    'Wild Discovery',
    'Wilo Lebanon',
    'Wines of Lebanon',
    'WISE - Moscanet',
    'Wookood Petroleum',
    'World Design Organization',
    'World Health Organization',
    'World House of Lebanon',
    'Wunderman Thompson',
    'YAZConsult',
    'Yelloblue',
    'Zarqa Provate University',
    'Zimmer Biomet',
    'Zmerly & Co',
    'Zoghzoghi Group',
    'ZR Group Holding',
    'Autre',
  ],
  experience_company_en: [
    '',
    '301 Entertainment',
    '3A Solutions Group',
    'A.N. Boukather',
    'A+ Management',
    'Abbott Laboratories',
    'Abboud Law Offices',
    'ABC',
    'Abela Assurances',
    'Abi Haidar Law Firm',
    'Abi Haila & Issa Co',
    'Abington Advisory',
    'Abniah',
    'Abou Jaoude and Associates Law Firm',
    'Aboujaoudé Hospital',
    'Abou Sleiman & Co',
    'ACT- Automation & Computer Technologies',
    'ACTED',
    'Acteos Liban',
    'Actuscope',
    'Adir Insurance',
    'Adline Media Network',
    'ADMIC',
    'ADPI Middle East',
    'Adwan Law Firm',
    'Agility Logistics',
    'Ahli International Bank',
    'AIG (Africa International Group)',
    'Air France',
    'Air Liquide',
    'Aishti',
    'Aksys Capital',
    'Al Akhbar',
    'Al Borj Hospital',
    'Al Makassed General Hospital',
    'Al Manar University',
    'Al Mashrek Insurance',
    'Al Mawarid Bank',
    'Al Mayyas Hospital',
    'Al Rassoul Al Azam Hospital',
    'Al Salam Hospital',
    'Al Wadi Al Akhdar',
    'Alaeddine Hospital',
    'Alargan',
    'Albani Engineering and Contracting',
    'Albert Massaad',
    'Alem & Associates',
    'Alfa Telecommunications',
    'Algorithm',
    'Ali Al Aidarous International Legal Practice',
    'Alico (American Life Insurance Company)',
    'Allianz SNA',
    'AltCity',
    'Alternite',
    'Al-Zahraa Hospital University Medical Center',
    'AMB Group',
    'Ambassade de Belgique au Liban',
    'Ambassade de France au Liban',
    'American Express',
    'AMNCC Law Firm',
    'ANGLESDIFFERING',
    'Annahar',
    'Antoine Chakhtoura Law Office',
    'Apave',
    'Apliman',
    'Apps2you',
    'Appwe Offices',
    'Arab BVank',
    'Arab Finance House',
    'Arab Scientific Publishers',
    'Arabia Insurance',
    'Arago Beirut Law Firm',
    'Aramex',
    'Arcenciel (NGO)',
    'Arope Insurance',
    'Assaf Law Firm',
    'Assurex Insurance and Reinsurance',
    'AstraZeneca',
    'Astrolabe ICT',
    'AUB',
    'AUBMC',
    'Auto Mall',
    'Automatix',
    'Averda House Beirut',
    'Axa Middle East',
    'Ayadina Association',
    'Azadea Group',
    'Bader Farhat Law Office',
    'Baker Tilly Zacca',
    'Banako',
    'Bank Audi',
    'Bank of Beirut',
    'Bankmed',
    'Banque BEMO',
    'Banque de Syrie et du Liban Finance',
    'Banque du Liban',
    'Banque Libano-Francaise',
    'Barclays Wealth',
    'Basil Soda',
    'Bassoul Heneine',
    'BBAC',
    'BCC Logistics',
    'BCom Offshore',
    'Beam International',
    'Beirut Container Terminal Consortium (BCTC)',
    'Beirut General Hospital',
    'Bel Group',
    'Best Assistance',
    'Best Food Plus Group',
    'Best Seller United Middle East',
    'Beyond Reform and Development',
    'BIM-ME',
    'Bint Jbeil Governmental Hospital',
    'Bioscientia',
    'Black Unicorn Media FZ LLC',
    'BLC Bank',
    'Bleu Design Consultants',
    'B-Line Medical',
    'BLOM Bank',
    'Blossom Agency',
    'BML - Banque Misr Liban',
    'Boecker',
    'Bou Khalil Societe Moderne',
    'Boulos Law Firm',
    'Boustany Trading and Services',
    'Brasserie Almaza',
    'BRICS',
    'Bringerr',
    'Bristish Council',
    'British American Tobacco (BAT)',
    'Broadgate Advisers',
    'Brokers XP',
    'BSEC - Bemo Securitization',
    'BUS Architects',
    'BUTEC',
    'Byblos Bank',
    'Byzance',
    'Cadis',
    'Capital Banking Solutions',
    'Cartier',
    'CD Log',
    'Cedarland Hotel',
    'Cedarwood Advisors',
    'Centre Hospitalier de Bhannes',
    'Century Travel',
    'CFI Lebanon - Credit Financier Invest',
    'Chalhoub Group',
    'Chanel',
    'Chaoui Holding',
    'Chedid Capital Holding',
    'Chehab Law Firm',
    'Chemonics Lebanon',
    'Chris and George Consulting and Trading',
    'Chronic Care Center',
    'Ciment de Sibline',
    'Cimenterie Nationale',
    'Clemenceau Medical Center - CMC',
    'Clinical and Diagnostics Logistics',
    'Clinique Du Levant',
    'CMA CGM',
    'CNAM',
    'CNR Marketing Group',
    'Code Fish',
    'Coeficient',
    'Collège Des Soeurs De Sainte Thérèse - Amioun',
    'Commercial Insurance',
    'Communication & Media Consulting Services',
    'Concrete Plus',
    'Conserves Modernes Chtaura',
    'Contracting & Trading Co C.A.T.',
    'Cortbawi Hospital',
    'Corum Group Ltd.',
    'Cre8mania - Digital Agency',
    'Credex',
    'Credit Bank',
    'Credit Financier',
    'Credit Libanais',
    'Credit Suisse',
    'Crepaway',
    'Crown Flour Mills',
    'CSCBank',
    'CSR (Al Ahli Holding Group)',
    'Dagher Capital',
    'Dallaa General Hospital',
    'Dar Al Shifaa Hospital',
    'Dar El Kotob',
    'Dataquest',
    'Debbane Saikali Group',
    'Debbas Group',
    'Debi.R',
    'Debs & Associates Law Firm',
    'Degrémont',
    'Deloitte',
    'Design Engineering Partners',
    'Destinators',
    'DG Jones And Partners',
    'Diageo',
    'Digmatech',
    'Dip To Color sal',
    'Diwanee',
    'DNA Training &Consulting',
    'Doctors Without Borders',
    'Dow',
    'Dubai Financial Service Authority',
    'Edarat Group',
    'Edenred Liban',
    'Eiwan United Trading &Contracting',
    'El Youssef Hospital Center',
    'Eli Lilly',
    'Endeavor Lebanon',
    'ENSOL',
    'eProseed Group',
    'Eptalex - Aziz Torbey Law Firm',
    'Ericsson',
    'E-Square Architects',
    'Etablissements Antoine Massoud (EAM)',
    'Exotica',
    'Experts Health Beauty',
    'Faden Advertising Ageny',
    'Fakhry General Contracting',
    'Fakhry Law Firm',
    'Farah & Chidiac Law Firm',
    'Fares Group Law Firm',
    'Fast Bollore Logistics',
    'Fattal Group',
    'Fawaz Holding',
    'Fayad Food Consulting',
    'Fenicia Bank',
    'FFA Private Bank',
    'Fidelity Insurance',
    'Firefly International',
    'First National Bank',
    'FISHEYE MediaLab',
    'FMCP',
    'Fondation Saradar',
    'FOO_',
    'Four Points by Sheraton',
    'Four Seasons Hotel Beirut',
    'Fransabank',
    'Freelance',
    'FXCM Trading',
    'G. Tamer Holding',
    'Gates Corporation',
    'Gazprombank',
    'Gefinor Rotana',
    'Gemayel Law Firm',
    'General Medical Equipment',
    'General Reinsurance Services',
    'GeoSpatial Minds',
    'Girardo Co.',
    'Global Protection Corp.',
    'GlobalCom Holding',
    'GlobeMed',
    'Globini for Travel & Tourism',
    'Gras Savoye Liban',
    'Green & Co.',
    'Greenpeace',
    'GS Stores',
    'GSS International',
    'Gulf Finance & Investment Company',
    'GWR Consulting',
    'Habib Betinjaneh Est.',
    'Haddad & Associates Law Firm',
    'Hafez Group',
    'Harb Law Firm',
    'Haroun Studios',
    'Havas Group',
    'Havi Global Solutions',
    'Hayek Hospital',
    'Hoballah Law Firm',
    'HODICO',
    'Holcim',
    'HOLDAL Group',
    'Home Mobility',
    'Hôpital Al Koura',
    'Hôpital des Soeurs du Rosaire',
    'Hôpital du Sacré Coeur',
    'Hopital Haroun',
    'Hôpital Hôtel Dieu de France',
    'Hôpital Saint Georges - Ajaltoun',
    'Hôpital Saint Joseph',
    'HSBC',
    'I Production',
    'ICTN',
    'ID Project',
    'Impact BBDO',
    'Imperial Jet',
    'INDEVCO Group',
    'Inria',
    'Institut des Finances Basil Fuleihan',
    'Integrated Systems',
    'Integrity',
    'InterContinental Phoenicia Beirut',
    'Intermedic (Jean Farah & Co.)',
    'International Consolidated Contractor (ICC)',
    'International Publishers',
    'Intrasky',
    'Invigo',
    'IP Engineering Pro',
    'IPEC',
    'IPSOS',
    'IPT Powertech Group',
    'ITec',
    'ITG Holding',
    'Jabal Amel Hospital',
    'Jetex',
    'Jimmy Choo',
    'Joaillerie Moukarzel',
    'Joe Fish Agency',
    'Johnson and Johnson',
    'K Group Holding',
    'Kafalat',
    'Kallas Law Firm',
    'Kallassi Group',
    'Kawas Consulting',
    'Kazar - Marble, Granite & Fireplace',
    'KBP-Biomak',
    'Kearney',
    'Keeward',
    'Kempinski Summerland Hotel &Resort',
    'Kettaneh Group',
    'Khatib and Alami',
    'Khoury General Hospital',
    'Khoury Home',
    'KidzMondo',
    'Kiyan Art',
    'Klimos Law Firm',
    'Knauf SCC',
    'Knowledge Development Company',
    'KStars Cosmetics',
    'La 16 Sal - Insurance Consultants',
    'La Constructa',
    'La Ferme Saint Jacques',
    'La Regie Libanaise de Publicité',
    'Laceco',
    "L'Atelier RosArt",
    'LAU - Lebanese American University',
    'Leader Group',
    'Lebanese Army',
    'Lebanese Development Network - LDN',
    'Lebanese Franchise Association',
    'Lebanese League for Women in Business (LLWB)',
    'Lebanese Order of Physicians',
    'Lebanese Red Cross',
    'Lebanese Swiss Bank',
    'Lebanese University',
    'Lebanon and Gulf Bank (LGB)',
    'Lebanon Heart Hospital',
    'LebVision',
    'Leo Burnett',
    'Les Plumes Galerie Elsie Braidi',
    'Les Volailles De Batroun',
    'Lesco ME',
    'Levant Law Practice',
    'Level 5 Holding',
    'LIA Insurance',
    "Libano Française d'Ingenierie (LFI)",
    'Libano-Suisse Insurance',
    'LibanPost',
    'Libnor',
    'Librairie Antoine',
    'Librairie Du Liban Publishers',
    'Librairie Orientale',
    'Librairie Stephan',
    'LITAT Group',
    "L'OR Espresso",
    'Luxury Selections',
    'M&C Saatchi',
    'M. Ezzat Jallad & Fils',
    'MaaDATA Group',
    'Maalouf and Associates Law Firm',
    'Machmouchi & Associates Law Firm',
    'Makassed University of Beirut',
    'Malia Group',
    'MaliaTec',
    'Maliks',
    'MAN Enterprise',
    'Manzil Home Health Services',
    'Maria Group',
    'Master Capital group',
    'MATEC',
    'Matta et Associés',
    'MEAB',
    'Medevco',
    'Medgulf',
    'Medial Collateral Ligament (MCL)',
    'MEDICA',
    'Medical Shares Trading',
    'Memac Ogilvy',
    'Mena Marketing',
    'Mentor Arabia',
    'Mersaco',
    'Method M',
    'Mets Holding',
    'MG Holding',
    'Middle East Airlines (MEA)',
    'Middle East Capital Group (MECG)',
    'Mideast Assistance International',
    'Miel du Levant',
    'Mike Sport',
    'Mind The Gap',
    'Ministry of Education and Higher Education',
    'MIRROS Communications',
    'MItchell Cosmetics Inc.',
    'Mitsulift and Equipment',
    "MK Cuisines D'allemagne",
    'Mm Hechme Logistics',
    'Mokbel Group',
    'Momentis Systems',
    'Monla Hospital',
    'Monty Mobile',
    'Mouawad Library',
    'Mount Lebanon Hospital',
    'Mövenpick Hotels & Resorts',
    'Murex',
    'Najjar Hospital',
    'Najm Engineering &Contracting',
    'Nasser &Associates Law Firm',
    'Natagri',
    'Natgaz',
    'National Automated Systems N.A.S.',
    'National Bank of Abu Dhabi',
    'National Bank of Kuwait',
    'National Social Security Fund (NSSF)',
    'NavLink',
    'Near East Consulting Group',
    'Nehme & Associates',
    'Nesma Trading Co. Ltd.',
    'Nestlé',
    'Netiks International',
    'New Mazloum Hospital',
    'Nexmedia',
    'Nexty Electronics',
    'Nielsen Holdings',
    'Nini Hospital',
    'Nobrand Agency',
    'Noueihed Law Firm',
    'Noura',
    'Obegi Consumer Products Holding',
    'Obegi Group',
    'Octapharma AG',
    'Office of Inspector General',
    'Optimedia',
    'Optiva',
    'Oracle',
    'Orange Business Services',
    'Oursin Boursin',
    'Patchi',
    'Peri Lebanon',
    'Perrin Paris',
    'Petroserv Limited',
    'Pharma Group',
    'Pharmacie Sacré Coeur',
    'Pharmadex',
    'Pharmaline',
    'Pharmamed',
    'Phoenicia Aer Rianta (PAC)',
    'Phoenicia University',
    'Phoenix Clinical Research',
    'Pikasso',
    'Plan Bee Architecture',
    'Plexi Pro',
    'Porsche',
    'Powertech',
    'Pragma Group',
    'Procter & Gamble Levant',
    'Prodent',
    'Promedz',
    'Promo House Group',
    'PSI',
    'Purple Martin',
    'QuanTech',
    'Raëd Abillama Architects',
    'Raee Hospital',
    'Rafic Gazzaoui & Co.',
    'Rafik Hariri University Hospital',
    'Rahma Medical Center',
    'Raidy Printing Group',
    'Ras Beirut Food Concepts',
    'Rectangle Jaune',
    'RELKO Ltd.',
    'REMCO',
    'Rim',
    'Roadster diner & Deek Duke',
    'Roche Lebanon',
    'Roger Najjar Law Firm',
    'Rotana Hotels',
    'RPS Research France',
    'RSM Global',
    'Russian Post',
    'SAAS Lawyers',
    'SABIS Educational Services',
    'Sabre Travel Network',
    'Safieddine Khoury & Jezzini Law Firm',
    'Safir Heliopolitan',
    'Sahel General Hospital',
    'Saint Charles Hospital',
    'Saint George Hospital',
    'Sakr Power Generation',
    'Sakr Real Estate',
    'Saltek - Bakery Equipment',
    'Sama Lel Tayaran',
    'Sami Nahas Law Firm',
    'Sami Pharmacy',
    'Samir Khairallah & Partners',
    'Sanofi Aventis',
    'Saradar Bank',
    'Sarkis Group International',
    'Saudi Build Co.',
    'Sawan Jewellery',
    'Schneider Electric',
    'SDC Group',
    'Sealine',
    'SEG Lebanon',
    'Segenius',
    'Setraco Group',
    'SGR',
    'Signature Productions',
    'Sir Dannieh Governmental Hospital',
    'Site Technology',
    'SM Architects',
    'SMLC PepsiCo',
    'SNB - Saudi National Bank',
    'Snowball',
    'Société Générale de Banque au Liban (SGBL)',
    'Société Orientale des Métaux Précieux (SOMP)',
    'Socodile Holding',
    'Sodamco Holding',
    'SoftMind',
    'Solidere',
    'Somfy Lebanon',
    'Spine Care Centre',
    'Spinneys',
    'SSK Law Firm',
    'SSS - Smart System Solution',
    'Stad Beirut',
    'Standard Chartered',
    'Storm Advertising & Design',
    'Sukleen',
    'SV Properties & Construction',
    'Tamyras',
    'TaraDomus',
    'Technica International',
    'Tehaco',
    'Tel Chiha Hospital',
    'Telesupport International (TSI)',
    'Terre Brune Hotel',
    'The EuroMena Funds',
    'The Lebanese Credit Insurer (LCI)',
    'The Webcor Group',
    'Thomson Reuters Corporation',
    'Tohme Law Firm',
    'Total Liban',
    'Trafigura Beheer BV',
    'Triple C',
    'Tripoli Governmental Hospital',
    'TVM Capital Healthcare',
    'Tyan & Zgheib Law Firm',
    'Unilever',
    'UNIPAK',
    'Unipharm',
    'Unitech International',
    'United Nations Development Programme (UNDP)',
    'United Nations Interim Force In Lebanon - UNI',
    'USJ - Saint Joseph University',
    'Vita Nova',
    'Vitality Clinic',
    'Voice of Lebanon',
    'Waked Law Firm',
    'Walid Haddad & Associates Law Firm',
    'War Child Holland',
    'Wardieh Holdings Inc Head-Office',
    'Wataniya Group',
    'Wezank',
    'Wheelers.me',
    'Wild Discovery',
    'Wilo Lebanon',
    'Wines of Lebanon',
    'WISE - Moscanet',
    'Wookood Petroleum',
    'World Design Organization',
    'World Health Organization',
    'World House of Lebanon',
    'Wunderman Thompson',
    'YAZConsult',
    'Yelloblue',
    'Zarqa Provate University',
    'Zimmer Biomet',
    'Zmerly & Co',
    'Zoghzoghi Group',
    'ZR Group Holding',
    'Other',
  ],
  universities_eng: [
    '',
    'Académie de Versailles',
    'AICPA - American Institute of CPAs',
    'Aix-Marseille Université',
    'Al Kafaat University',
    'ALBA - Université de Balamand',
    'American University Washington D.C',
    'AOU - Arab Open University',
    'AUB - American University of Beirut',
    'AUCE - American University of Culture & Educa',
    'AUL - Arts Sciences and Technology University',
    'AUST - American University of Science and Technology',
    'Barrington University',
    'BAU - Beirut Arab University',
    'BCU - Birmingham City University',
    'BEM - Bordeaux Management School',
    'Boston University',
    'Business & Computer University',
    'C&E - American University Institute',
    'California Lutheran University',
    'Cardiff Metropolitan University',
    "Carleton University-Canada's Capital University",
    'Case Western reserve University ',
    'CEIBS-China Europe International Business Sch',
    'CEL - California Eastern Laboratories',
    'Centre des Hautes Etudes de Construction',
    'City, University of London',
    'Clemson University',
    'CLET- Collège for Law, Education and Training',
    'CNAM-Conservatoire national des arts et métiers',
    'Collège des Saints Cœurs Sioufi',
    'Columbia University',
    'Concordia University',
    'Damascus University',
    'DePaul University',
    'EAC Business School of Arts, Culture & Luxury',
    'Ecole BTS Toulouse | ESARC Evolution',
    'Ecole de Commerce ISEG Business & Finance',
    'Ecole des Mines de Saint-Etienne',
    'Ecole Hôtelière de Lausanne',
    'Ecole Intuit Lab',
    'Ecole Navale Pigier',
    'Ecole Polytechnique',
    'eCornell - Cornell University',
    'ECPM',
    'ECV - Ecole de Communication Visuelle',
    'EDHEC Business School',
    "EFET-Ecole Française d'Enseignement Technique",
    'EGC - Ecole de Gestion et de Commerce',
    'EIML-Ecole Internationale de Marketing du Lux',
    'ENSAIA Université de Lorraine',
    'ENST - Ecole Nationale Supérieure en Telecom',
    'Erasmus University Rotterdam',
    'ESA Business School',
    'ESB - Ecole Supérieure de Banques',
    'ESC Toulouse Business School',
    'ESCP Europe Business School',
    'ESIGETEL',
    "ESILV - Ecole d'Ingénieurs Paris - La Défense",
    'ESLSCA Business School',
    'ESMA-Ecole Supérieure des Métiers Artistiques',
    'ESMK-Ecole Supérieure de Management de Kinshasa',
    'Esmod Fashion University',
    'ESSEC Business School',
    'FAU - Florida Atlantic University',
    'Filière Francophone de Droit',
    'GARP-Global Association of Risk Professionals',
    'George Washington University',
    'Georgia Institute of Technology',
    'Georgia State University',
    'GIA - Gemological Institute of America',
    'Glion Hotel Management School',
    'Global University',
    'Grenoble Graduate School of Business (ESC)',
    'Haigazian University',
    'Harvard University',
    'Haute Ecole Paul-Henri Spaak',
    'HEC Paris',
    'HIM - Hotel Institute Montreux',
    'ICN Business School Nancy',
    'IESE Business School',
    'IFEC -Institut Franco-Européen de Chiropraxie',
    'IFM - Institut Français de la Mode',
    'IFMK Lariboisière',
    'INP-Institut National Polytechnique Félix(HB)',
    'INSA-Institut National des Sciences Appliquée',
    'INSEAD Business School',
    'Inseec Business School',
    'INSIM',
    'International University of Monaco',
    'IPNET - Dekwaneh',
    'ISAM',
    'ISC-GOMBE Institut Supérieur de Commerce',
    'ISEM',
    'Istituto Marangoni',
    'IUL - Islamic University of Lebanon',
    'Jordan University of Science and Technology',
    'Kursk State University',
    'LAU - Lebanese American University',
    'LBS - London Business School',
    'LCU - Lebanese Canadian University',
    'Le Cordon Bleu',
    'Lebanese University',
    'Les Roches School of Hotel Management',
    'LGU - Lebanese German University',
    'LIU - Lebanese International University',
    'LLFP - Lycée Libanais Francophone Privé',
    'LSE - London School of Economics',
    'Lviv National Medical Institute',
    'Maastricht School Of Management (MSM)',
    'McGILL University',
    'MECAT',
    'Medicine School of Tunis',
    'MEU - Middle east University',
    'Michigan State University',
    'MINES ParisTech',
    'Minia University',
    'Montclair State University',
    'Morgan International',
    'MUBS-Modern University for Business and Science',
    'Musicians Institute',
    'NDU - Notre Dame University',
    'Newport University CED',
    'NYU Stern School of Business',
    'Oxford Brookes University',
    'Project Management Institute (PMI)',
    'Protestant University',
    'Rafik Hariri University',
    'RMS - Reims Management School',
    'Rostov State Medical University',
    'Rotterdam University',
    'Royal Holloway University of London',
    'San Francisco State University',
    'Sapienza - Università di Roma',
    'Sciences-Po Paris',
    'Sherbrooke academy',
    'SKEMA Business School',
    "St. George's University",
    'State University of New York',
    'Strathclyde Business School',
    'Studio Berçot',
    'Syiah Kuala University',
    'Texas A&M University',
    'The International University Missouri',
    'Tishreen University',
    'UAL- London Collège of Fashion',
    'UFL - University of Florida',
    'UFU - Universidade Federal de Uberlândia',
    'UMEA University',
    'Universidad de Sevilla',
    'Università di perugia',
    'Université Antilles-Guyane',
    'Université de Bretagne Occidentale',
    'Université de Damas',
    'Université de DSCHANG',
    'Université de Genève',
    'Université de Jordanie',
    'Université de Kinshasa',
    'Université de Liège',
    'Université de Lille',
    'Université de Lomé',
    'Université de Montpellier',
    'Université de Montréal',
    'Université De Mulhouse',
    'Université de Nantes - Polytech Nantes',
    'Université de Ngaoundéré',
    'Université de Nice',
    'Université de Ouagadougou',
    'Université de Québec à Chicoutimi',
    'Université de Rouen Normandie',
    'Université de Séville',
    'Université de technologie Belfort- Montbéliard',
    'Université du Caire',
    'Université du Québec à Montréal - UQAM',
    'Université François-Rabelais',
    'Université Jean Monnet',
    'Université Jean Monnet – Saint Etienne',
    'Université Louis Pasteur',
    'Université Lumière Lyon 2',
    'Université Marien Ngouabi',
    'Université Paris Ouest Nanterre La Défense',
    'Université Paris-Dauphine',
    'Université Picardie Jules verne',
    'Université Pierre et Marie Curie',
    'Université Toulouse 1 Capitole',
    'Université Toulouse III - Paul Sabatier',
    'Université Versailles Saint-Quentin',
    'Université de Poitiers',
    'University of Akron',
    'University of Aleppo',
    'University of Atlanta',
    'University of Buckingham',
    'University of California',
    'University of Cambridge',
    'University of Catania',
    'University of Central Florida',
    'University of Ghana',
    'University of Isfahan - Iran',
    'University of Liverpool',
    'University of Massachusetts Boston',
    'University of Nevada Las Vegas',
    'University of Northwest',
    'University of Ottawa',
    'University of Phoenix Arizona',
    'University of Portsmouth',
    'University of Reading',
    'University of Sunderland',
    'University of Surrey',
    'University of Technology Sydney',
    'University of the Punjab',
    'University of Tripoli',
    'University of York',
    'University of Oslo',
    'University of Strasbourg',
    'UPA - Université Antonine',
    'UPJV - Université de Picardie Jules Verne',
    'UPJV- Université de Picardie Jules Verne',
    'USC - University of Southern California',
    'USEK - Université Saint Esprit de Kaslik',
    'USF - Université de la Sainte Famille',
    'USJ - Saint Joseph University',
    'Wayne State University',
    'Wisconsin International University Collège',
    'Wright State University - USA',
    'Zarqa Private University',
    'Other',
  ],

  universities_fr: [
    '',
    'Académie de Versailles',
    'AICPA - American Institute of CPAs',
    'Aix-Marseille Université',
    'Al Kafaat University',
    'ALBA - Université de Balamand',
    'American University Washington D.C',
    'AOU - Arab Open University',
    'AUB - American University of Beirut',
    'AUCE - American University of Culture & Educa',
    'AUL - Arts Sciences and Technology University',
    'AUST - American University of Science and Technology',
    'Barrington University',
    'BAU - Beirut Arab University',
    'BCU - Birmingham City University',
    'BEM - Bordeaux Management School',
    'Boston University',
    'Business & Computer University',
    'C&E - American University Institute',
    'California Lutheran University',
    'Cardiff Metropolitan University',
    "Carleton University-Canada's Capital University",
    'Case Western reserve University ',
    'CEIBS-China Europe International Business Sch',
    'CEL - California Eastern Laboratories',
    'Centre des Hautes Etudes de Construction',
    'City, University of London',
    'Clemson University',
    'CLET- Collège for Law, Education and Training',
    'CNAM-Conservatoire national des arts et métiers',
    'Collège des Saints Cœurs Sioufi',
    'Columbia University',
    'Concordia University',
    'Damascus University',
    'DePaul University',
    'EAC Business School of Arts, Culture & Luxury',
    'Ecole BTS Toulouse | ESARC Evolution',
    'Ecole de Commerce ISEG Business & Finance',
    'Ecole des Mines de Saint-Etienne',
    'Ecole Hôtelière de Lausanne',
    'Ecole Intuit Lab',
    'Ecole Navale Pigier',
    'Ecole Polytechnique',
    'eCornell - Cornell University',
    'ECPM',
    'ECV - Ecole de Communication Visuelle',
    'EDHEC Business School',
    "EFET-Ecole Française d'Enseignement Technique",
    'EGC - Ecole de Gestion et de Commerce',
    'EIML-Ecole Internationale de Marketing du Lux',
    'ENSAIA Université de Lorraine',
    'ENST - Ecole Nationale Supérieure en Telecom',
    'Erasmus University Rotterdam',
    'ESA Business School',
    'ESB - Ecole Supérieure de Banques',
    'ESC Toulouse Business School',
    'ESCP Europe Business School',
    'ESIGETEL',
    "ESILV - Ecole d'Ingénieurs Paris - La Défense",
    'ESLSCA Business School',
    'ESMA-Ecole Supérieure des Métiers Artistiques',
    'ESMK-Ecole Supérieure de Management de Kinshasa',
    'Esmod Fashion University',
    'ESSEC Business School',
    'FAU - Florida Atlantic University',
    'Filière Francophone de Droit',
    'GARP-Global Association of Risk Professionals',
    'George Washington University',
    'Georgia Institute of Technology',
    'Georgia State University',
    'GIA - Gemological Institute of America',
    'Glion Hotel Management School',
    'Global University',
    'Grenoble Graduate School of Business (ESC)',
    'Haigazian University',
    'Harvard University',
    'Haute Ecole Paul-Henri Spaak',
    'HEC Paris',
    'HIM - Hotel Institute Montreux',
    'ICN Business School Nancy',
    'IESE Business School',
    'IFEC -Institut Franco-Européen de Chiropraxie',
    'IFM - Institut Français de la Mode',
    'IFMK Lariboisière',
    'INP-Institut National Polytechnique Félix(HB)',
    'INSA-Institut National des Sciences Appliquée',
    'INSEAD Business School',
    'Inseec Business School',
    'INSIM',
    'International University of Monaco',
    'IPNET - Dekwaneh',
    'ISAM',
    'ISC-GOMBE Institut Supérieur de Commerce',
    'ISEM',
    'Istituto Marangoni',
    'IUL - Islamic University of Lebanon',
    'Jordan University of Science and Technology',
    'Kursk State University',
    'LAU - Lebanese American University',
    'LBS - London Business School',
    'LCU - Lebanese Canadian University',
    'Le Cordon Bleu',
    'Lebanese University',
    'Les Roches School of Hotel Management',
    'LGU - Lebanese German University',
    'LIU - Lebanese International University',
    'LLFP - Lycée Libanais Francophone Privé',
    'LSE - London School of Economics',
    'Lviv National Medical Institute',
    'Maastricht School Of Management (MSM)',
    'McGILL University',
    'MECAT',
    'Medicine School of Tunis',
    'MEU - Middle east University',
    'Michigan State University',
    'MINES ParisTech',
    'Minia University',
    'Montclair State University',
    'Morgan International',
    'MUBS-Modern University for Business and Science',
    'Musicians Institute',
    'NDU - Notre Dame University',
    'Newport University CED',
    'NYU Stern School of Business',
    'Oxford Brookes University',
    'Project Management Institute (PMI)',
    'Protestant University',
    'Rafik Hariri University',
    'RMS - Reims Management School',
    'Rostov State Medical University',
    'Rotterdam University',
    'Royal Holloway University of London',
    'San Francisco State University',
    'Sapienza - Università di Roma',
    'Sciences-Po Paris',
    'Sherbrooke academy',
    'SKEMA Business School',
    "St. George's University",
    'State University of New York',
    'Strathclyde Business School',
    'Studio Berçot',
    'Syiah Kuala University',
    'Texas A&M University',
    'The International University Missouri',
    'Tishreen University',
    'UAL- London Collège of Fashion',
    'UFL - University of Florida',
    'UFU - Universidade Federal de Uberlândia',
    'UMEA University',
    'Universidad de Sevilla',
    'Università di perugia',
    'Université Antilles-Guyane',
    'Université de Bretagne Occidentale',
    'Université de Damas',
    'Université de DSCHANG',
    'Université de Genève',
    'Université de Jordanie',
    'Université de Kinshasa',
    'Université de Liège',
    'Université de Lille',
    'Université de Lomé',
    'Université de Montpellier',
    'Université de Montréal',
    'Université De Mulhouse',
    'Université de Nantes - Polytech Nantes',
    'Université de Ngaoundéré',
    'Université de Nice',
    'Université de Ouagadougou',
    'Université de Québec à Chicoutimi',
    'Université de Rouen Normandie',
    'Université de Séville',
    'Université de technologie Belfort- Montbéliard',
    'Université du Caire',
    'Université du Québec à Montréal - UQAM',
    'Université François-Rabelais',
    'Université Jean Monnet',
    'Université Jean Monnet – Saint Etienne',
    'Université Louis Pasteur',
    'Université Lumière Lyon 2',
    'Université Marien Ngouabi',
    'Université Paris Ouest Nanterre La Défense',
    'Université Paris-Dauphine',
    'Université Picardie Jules verne',
    'Université Pierre et Marie Curie',
    'Université Toulouse 1 Capitole',
    'Université Toulouse III - Paul Sabatier',
    'Université Versailles Saint-Quentin',
    'Université de Poitiers',
    'University of Akron',
    'University of Aleppo',
    'University of Atlanta',
    'University of Buckingham',
    'University of California',
    'University of Cambridge',
    'University of Catania',
    'University of Central Florida',
    'University of Ghana',
    'University of Isfahan - Iran',
    'University of Liverpool',
    'University of Massachusetts Boston',
    'University of Nevada Las Vegas',
    'University of Northwest',
    'University of Ottawa',
    'University of Phoenix Arizona',
    'University of Portsmouth',
    'University of Reading',
    'University of Sunderland',
    'University of Surrey',
    'University of Technology Sydney',
    'University of the Punjab',
    'University of Tripoli',
    'University of York',
    'University of Oslo',
    'University of Strasbourg',
    'UPA - Université Antonine',
    'UPJV - Université de Picardie Jules Verne',
    'UPJV- Université de Picardie Jules Verne',
    'USC - University of Southern California',
    'USEK - Université Saint Esprit de Kaslik',
    'USF - Université de la Sainte Famille',
    'USJ - Saint Joseph University',
    'Wayne State University',
    'Wisconsin International University Collège',
    'Wright State University - USA',
    'Zarqa Private University',
    'Autre',
  ],

  experience_experienceType: [
    '',
    'Internship',
    'Full Time',
    'Part Time',
    'Training',
  ],

  experience_position_en: [
    '',
    'Governors (Board)',
    'Executive',
    'Manager',
    'Employee',
    'Independent',
  ],

  experience_position_fr: [
    '',
    'Gouverneurs (Conseil)',
    'Exécutive',
    'Directrice',
    'Employé',
    'Indépendant',
  ],

  experience_FunctionalArea_en: [
    '',
    'Administration',
    'Arts and Culture',
    'Defense',
    'Digital Innovations',
    'Finance',
    'Health',
    'Human Resources',
    'Information Systems',
    'Legal',
    'Logistics-Supply chain',
    'Marketing / Communication',
    'Politics / Diplomacy',
    'Strategy',
  ],

  experience_FunctionalArea_fr: [
    '',
    'Administration',
    'Arts et Culture',
    'La Défense',
    'Innovations numériques',
    'Finance',
    'Santé',
    'Ressources Humaines',
    'Information Systems',
    "Systèmes d'information",
    'Logistique-Supply chain',
    'Marketing / Communication',
    'Politique / Diplomatie',
    'Stratégie',
  ],

  experience_businessActivity_en: [
    '',
    'Advertising / Marketing',
    'Agrifood',
    'Army',
    'Association / NGO / Syndicate / Order',
    'Banking',
    'Commerce / Retail / Distribution',
    'Construction',
    'Consulting',
    'Audit',
    'Culture / Arts / Craft',
    'Education / Training',
    'Embassy',
    'Energy',
    'Event planning',
    'Financial services',
    'Government / Public functions',
    'Health',
    'Hospitals / Medical Centers',
    'Restaurant / Café',
    'Independent business',
    'Industrial',
    'Insurance',
    'IT / Telecom',
    'Law / Legal services',
    'Maintenance / Security',
    'Media / Press',
    'Pharmaceutical',
    'Real Estate',
    'Services',
    'Sports',
    'Tourism / Travel',
    'Translation',
    'Transport',
  ],

  experience_businessActivity_fr: [
    '',
    'Marketing / Publicitaire',
    'Agroalimentaire',
    'Armée',
    'Association / ONG / Syndicat / Ordre',
    'Bancaire',
    'Commerce / Distribution / Distribution',
    'Construction',
    'Consultant',
    'Audit',
    'Culture / Arts / Artisanat',
    'Éducation / Formation',
    'Ambassade',
    'Énergie',
    "Planification d'événements",
    'Services financiers',
    'Gouvernement / Fonctions publiques',
    'Santé',
    'Hôpitaux / Centres Médicaux',
    'Restaurant / Café',
    'Entreprise indépendante',
    'Industriel',
    'Assurance',
    'Informatique / Télécom',
    'Droit / Services juridiques',
    'Entretien / Sécurité',
    'Médias / Presse',
    'Pharmaceutique',
    'Immobilier',
    'Prestations de Service',
    'Sports',
    'Tourisme / Voyage',
    'Traduction',
    'Transport',
  ],

  payment_en: [
    '',
    'Bank loan',
    'Personal savings',
    'Employer sponsorship (full or partial)',
    'Scholarship / Bourse',
    'Other',
  ],

  payment_fr: [
    '',
    'Prêt bancaire',
    'Epargne personnelle',
    'Financement par mon employeur (complet ou partiel)',
    'Bourse',
    'Autre',
  ],

  default_Country: 'Lebanon',
  default_Country_fr: 'Liban',

  // where_going_after_save_en: `/user/login`,
  where_going_after_save_en: '/user/login',
  where_going_after_save_fr: '/fr/user/login',
  going_to_external_URL: false,
  // going_to_external_URL_after_save_en: 'https://www.esa.edu.lb/english/home',
  // going_to_external_URL_after_save_fr: 'https://www.esa.edu.lb/french/home',

  where_going_after_submit: '/',
  // where_going_after_submit: '/user/login',
  // where_going_after_signin: '/',
  where_going_after_signin: '/user/studentapplication/routetoapp',

  // where_going_after_logout_en: '/',
  // where_going_after_logout_fr: '/',
  where_going_after_logout: '/user/login',

  where_going_onclicking_esa_logo: '/user/login',

  // where_going_wrong_major_by_URL: '/',
  where_going_wrong_major_by_URL: '/user/login',
  where_going_on_hacking_by_URL: '/user/login',

  auto_Save_Timing: [10 * 60 * 1000],
  auto_Save_Timing_firstTime: [20 * 1000],
  message_disapear_timing: [5 * 1000],
  message_disapear_timing_long: [9 * 1000],

  personalinfo_dob_min: ['1980-01-01'],
  personalinfo_dob_max: ['2006-10-31'],

  upload_file_single_size: [4 * 1024 * 1024],
  // Modified As per owner request
  upload_file_total_size: [4 * 1024 * 1024],
  upload_file_total_number: [1],

  // upload_file_total_size: [10 * 1024 * 1024],
  // upload_file_total_number: [10],
  upload_photo_type: '.png, .jpg, .jpeg',
  upload_file_type: '.pdf, .png, .jpg, .jpeg , .xlsx ,.csv',
  // upload_file_type: '.pdf, .png, .jpg, .jpeg,.doc,.docx',
  upload_photo_allowedExtensions: /(\.jpg|\.jpeg|\.png)$/i,
  upload_file_allowedExtensions: /(\.jpg|\.jpeg|\.png|\.pdf|\.xlsx|\.csv)$/i,
  // upload_file_allowedExtensions: /(\.jpg|\.jpeg|\.png|\.pdf|\.doc|\.docx)$/i,

  upload_file_mimetype: ['image', 'pdf', 'officedocument', 'msword'],
  // upload_file_directory_name: '/public/',

  // upload_file_directory_name: '/utilities/ConvertToPDF/assets/',
  upload_file_directory_name: '/uploads/',
  education_Year_of_Acquisition_Limit: [20],
  carouselList: [
    'https://res.cloudinary.com/ds6avfn6i/image/upload/v1672246403/esaonlineapp/carousel/ESA2_no985s.jpg',
    'https://res.cloudinary.com/ds6avfn6i/image/upload/v1672246438/esaonlineapp/carousel/ESA1_kvmcjd.jpg',
    'https://res.cloudinary.com/ds6avfn6i/image/upload/v1672251947/esaonlineapp/carousel/ESAInside15042019_rgjnkw.jpg',
    'https://res.cloudinary.com/ds6avfn6i/image/upload/v1672246438/esaonlineapp/carousel/ESA1_kvmcjd.jpg',
    'https://res.cloudinary.com/ds6avfn6i/image/upload/v1672251894/esaonlineapp/carousel/WhatsApp-Image-2020-04-17-at-4.12.09-PM_v4xgvt.jpg',
    'https://res.cloudinary.com/ds6avfn6i/image/upload/v1672251868/esaonlineapp/carousel/Portalis_mansion_tzt5ia.jpg',
  ],

  esa_logo:
    'https://res.cloudinary.com/ds6avfn6i/image/upload/v1672246197/esaonlineapp/public/esa_qwrigu.png',
  user_Avatar:
    'https://res.cloudinary.com/ds6avfn6i/image/upload/v1672246211/esaonlineapp/public/male_fozfl1.png',
  login_bg:
    'https://res.cloudinary.com/ds6avfn6i/image/upload/v1672434771/esaonlineapp/Login_background/lgin_hvpco4.png',
  MBA_recommendation_letter:
    'https://res.cloudinary.com/ds6avfn6i/image/upload/v1673539319/esaonlineapp/documents/ESA_template-MBA_Recommendation_Letter_aduwih.pdf',
  EMBA_recommendation_letter:
    'https://res.cloudinary.com/ds6avfn6i/image/upload/v1673539318/esaonlineapp/documents/ESA_template-EMBA_Recommendation_Letter_shqt8y.pdf',

  // cloud_Name:"dekceipha",
  // upload_preset: "ummmrnoi",
  // cloudinary_image_url: "https://api.cloudinary.com/v1_1/dekceipha/image/upload",
  // cloudinary_document_url: "https://api.cloudinary.com/v1_1/dekceipha/upload",isMongoDb: true,

  application_status: [
    '',
    'incomplete',
    'submitted',
    'complete',
    'qualified',
    'accepted',
    'obsolete',
  ],
  application_status_inList: [
    'incomplete',
    'submitted',
    'complete',
    'qualified',
    'accepted',
    'obsolete',
  ],
  Academic_program_inList: [
    'BBA (Bachelor in Business Administration)',
    'DBA (Doctorate in Business Administration)',
    // 'DU (Diplome Universitaire en Recherche)',
    'EMBA (Executive Masters in Business Administration)',
    'EMFM (Executive Master in Financial Management)',
    'MBA (Master in Business Administration)',
    'MEMS (Master Executif en Management de la Santé)',
    'MENT (Masters in Entrepreneurship)',
    'MIAD (Master in International Affairs and Diplomacy)',
    'MIM (International Masters In Management)',
    'MSM (Mastère de Spécialisation en Marketing et Communication)',
  ],

  Academic_program_Account: [
    {
      value: 'BBA (Bachelor in Business Administration)',
      label: 'BBA (Bachelor in Business Administration)',
    },
    {
      value: 'DBA (Doctorate in Business Administration)',
      label: 'DBA (Doctorate in Business Administration)',
    },
    {
      value: 'EMBA (Executive Masters in Business Administration)',
      label: 'EMBA (Executive Masters in Business Administration)',
    },
    {
      value: 'EMFM (Executive Master in Financial Management)',
      label: 'EMFM (Executive Master in Financial Management)',
    },
    {
      value: 'MBA (Master in Business Administration)',
      label: 'MBA (Master in Business Administration)',
    },
    {
      value: 'MEMS (Master Executif en Management de la Santé)',
      label: 'MEMS (Master Executif en Management de la Santé)',
    },
    {
      value: 'MENT (Masters in Entrepreneurship)',
      label: 'MENT (Masters in Entrepreneurship)',
    },
    {
      value: 'MIAD (Master in International Affairs and Diplomacy)',
      label: 'MIAD (Master in International Affairs and Diplomacy)',
    },
    {
      value: 'MIM (International Masters In Management)',
      label: 'MIM (International Masters In Management)',
    },
    {
      value: 'MSM (Mastère de Spécialisation en Marketing et Communication)',
      label: 'MSM (Mastère de Spécialisation en Marketing et Communication)',
    },
  ],
  pageSize: [10],
  search_limit: [30],
  max_characters_count: [3000],
  role: ['', 'Admin', 'Program Manager', 'Adminstrative'],
  adminDropDownList: [
    '',
    'Academic Program',
    'Emergency Contact Disease Type',
    'Education Baccalaureate Option',
    'Education Degree Level',
    'Education Degree Level BBA',
    'Education Institution',
    'Education Universities',
    'Field of Study',
    'Relationship',
    'Source',
    'Company',
    'Experience Type',
    'Position',
    'Functional Area',
    'Business Activity',
    'Payment',
  ],

  education_fieldOfStudy: [
    '',
    '3d animation',
    'Accounting',
    'Acting & Directing',
    'Actuarial Science',
    'Advertising & Marketing',
    'Agriculture',
    'Anesthesie-reanimation',
    'Arabic Language and Literature',
    'Archeology',
    'Architecture',
    'Artistic Director',
    'Agronomy',
    'Arts',
    'Astronomy',
    'Audiovisual',
    'Audit',
    'Banking & Finance',
    'Biochemistry',
    'Bioinformatics',
    'Biology',
    'Bio marketing',
    'Biomedical Sciences',
    'Business Analysis & Consulting',
    'Business Administration',
    'Business Law',
    'Chemistry',
    'Civil and Environmental Engineering',
    'Civil Engineering',
    'Communication Arts',
    'Applied and Computational Mathematics',
    'Computer Engineering',
    'Computer Science',
    'Conflict Analysis and Resolution',
    'Corporate Governance',
    'Cosmetology',
    'Credit Analysis',
    'Dental Medicine',
    'Dental Surgery',
    'Digital Marketing',
    'Digital Media',
    'Diplomacy and Strategic Negotiations',
    'Economics',
    'Education',
    'Electrical Engineering',
    'Elementary Education',
    'Engineering',
    'English',
    'Environmental Science',
    'Environmental Health',
    'Events Management',
    'Family Business and Entrepreneurship ',
    'Fashion Design',
    'Financial Engineering',
    'Food Industry',
    'French Literature',
    'General Surgery',
    'Geology',
    'Graphic Design',
    'Health Care',
    'Hematology',
    'History',
    'Hospitality and Tourism Management',
    'Human Resources',
    'Illustration & Comic',
    'Immunology',
    'Industrial Technology',
    'Information Technology',
    'Insurance',
    'Interior Design',
    'International Affairs',
    'Journalism',
    'Landscape design & eco-system management',
    'Law',
    'Liberal arts',
    'Luxury Management',
    'Management',
    'Marketing & Communication',
    'Mathematics',
    'Mechanical engineering',
    'Mechatronics',
    'Media',
    'Medicine',
    'Management Information systems',
    'Nursing',
    'Nutrition',
    'Oil & Gas',
    'Orthopedics',
    'Orthophonie',
    'Osteopathic',
    'Pediatric',
    'Pharmacy',
    'Physiotherapy',
    'Political Science',
    'Public Administration',
    'Social Science',
    'Sociology',
    'Special Education',
    'Statistics',
    'Strategy & Leadership',
    'Supply Chain & Distribution',
    'Telecommunications Engineering',
    'Television and Film',
    'Theater',
    'Translation',
    'Transport et Logistique',
    'Travel and Tourism',
    'Other',
  ],

  education_fieldOfStudy_fr: [
    '',
    '3d animation',
    'Accounting',
    'Acting & Directing',
    'Actuarial Science',
    'Advertising & Marketing',
    'Agriculture',
    'Anesthesie-reanimation',
    'Arabic Language and Literature',
    'Archeology',
    'Architecture',
    'Artistic Director',
    'Agronomy',
    'Arts',
    'Astronomy',
    'Audiovisual',
    'Audit',
    'Banking & Finance',
    'Biochemistry',
    'Bioinformatics',
    'Biology',
    'Bio marketing',
    'Biomedical Sciences',
    'Business Analysis & Consulting',
    'Business Administration',
    'Business Law',
    'Chemistry',
    'Civil and Environmental Engineering',
    'Civil Engineering',
    'Communication Arts',
    'Applied and Computational Mathematics',
    'Computer Engineering',
    'Computer Science',
    'Conflict Analysis and Resolution',
    'Corporate Governance',
    'Cosmetology',
    'Credit Analysis',
    'Dental Medicine',
    'Dental Surgery',
    'Digital Marketing',
    'Digital Media',
    'Diplomacy and Strategic Negotiations',
    'Economics',
    'Education',
    'Electrical Engineering',
    'Elementary Education',
    'Engineering',
    'English',
    'Environmental Science',
    'Environmental Health',
    'Events Management',
    'Family Business and Entrepreneurship ',
    'Fashion Design',
    'Financial Engineering',
    'Food Industry',
    'French Literature',
    'General Surgery',
    'Geology',
    'Graphic Design',
    'Health Care',
    'Hematology',
    'History',
    'Hospitality and Tourism Management',
    'Human Resources',
    'Illustration & Comic',
    'Immunology',
    'Industrial Technology',
    'Information Technology',
    'Insurance',
    'Interior Design',
    'International Affairs',
    'Journalism',
    'Landscape design & eco-system management',
    'Law',
    'Liberal arts',
    'Luxury Management',
    'Management',
    'Marketing & Communication',
    'Mathematics',
    'Mechanical engineering',
    'Mechatronics',
    'Media',
    'Medicine',
    'Management Information systems',
    'Nursing',
    'Nutrition',
    'Oil & Gas',
    'Orthopedics',
    'Orthophonie',
    'Osteopathic',
    'Pediatric',
    'Pharmacy',
    'Physiotherapy',
    'Political Science',
    'Public Administration',
    'Social Science',
    'Sociology',
    'Special Education',
    'Statistics',
    'Strategy & Leadership',
    'Supply Chain & Distribution',
    'Telecommunications Engineering',
    'Television and Film',
    'Theater',
    'Translation',
    'Transport et Logistique',
    'Travel and Tourism',
    'Autre',
  ],
  SLACK_WEBHOOK_URL:
    'https://hooks.slack.com/services/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',

  // Cloudinary Account For esaonlineapp2022@gmail.com
  cloud_Name: 'ds6avfn6i',
  upload_preset: 'mvermbgcesaonline',
  cloudinary_image_url:
    'https://api.cloudinary.com/v1_1/ds6avfn6i/image/upload',
  cloudinary_document_url: 'https://api.cloudinary.com/v1_1/ds6avfn6i/upload',
  isMongoDb: false,
  logger_expiry_day: '30d',
  logger_max_file_size: '20m',
  axios_timeout: [60000], // timeout in milliseconds
  logger_actions: [
    '',
    'account deleted',
    'account created',
    'account locked',
    'account unlocked',
    'account updated',
    'lists exported',
    'change student major',
    'change student status',
    'signup',
    'login',
    'signout',
    'signout navbar',
    'user signout due to Browser problem',
    'add reprotURl',
    'email Sent',
    'session expire',
    'update profile',
    'verifyemail',
    'email already verified',
    'password reseted',
    'password already reseted',
    'Read from DB',
    'autosave',
    'save',
    'submit',
    `switch to`,
  ],
  presence:[
    'Present',
    'Absent'
  ]
};

export default selection_data;
